site:
  title: Antora Docs
  start_page: main::main.adoc
content:
  sources:
  - url: https://github.com/cardoso-thiago/antora-docs-source1.git
    branches: main
  - url: https://github.com/cardoso-thiago/antora-docs-source2.git
    branches: main
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll